# Site settings
title: Kevin Wilson, MPH MS
tag_text: Kevin Wilson
description: Public health informatician, computer programmer, and epidemiologist with global health experience.
url: "https://kevinwilson.github.io"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
